"use strict";
exports.__esModule = true;
var CrearFiguras_1 = require("./CrearFiguras");
var creador = new CrearFiguras_1.CrearFigura();
var figura1 = creador.crear("a", 'Circulo', 8);
var figura2 = creador.crear("b", 'Cuadrado', 8);
figura1 === null || figura1 === void 0 ? void 0 : figura1.calcularArea();
figura1 === null || figura1 === void 0 ? void 0 : figura1.calcularPerimetro();
figura2 === null || figura2 === void 0 ? void 0 : figura2.calcularArea();
figura2 === null || figura2 === void 0 ? void 0 : figura2.calcularPerimetro();
